---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  - bash
  - networking-terms
  - python
  - words
  - "!aws"
  - "!backwards-compatibility"
  - "!cryptocurrencies"
  - "!cpp"
ignorePaths:
  # All dot files in the root
  - \.*
  # This file
  - cspell.config.yaml
  # The docs requirements file
  - docs/requirements.in
  # The mypy configuration file
  - mypy.ini
  # The shared file for tool configuration
  - pyproject.toml
  # requirements.txt is generated
  - .config/requirements.in*
